events {}

http {
    upstream storefront { server web:8000; }
    upstream catalog_service { server catalog:8001; }
    upstream order_service { server orders:8002; }
    upstream user_service { server users:8003; }
    upstream ai_service { server ai:8004; }
    upstream payment_service { server payments:8005; }
    upstream product_service { server products:8006; }
    upstream shipping_service { server shipping:8007; }

    server {
        listen 8080;

        location /catalog/ {
            rewrite ^/catalog/(.*)$ /$1 break;
            proxy_pass http://catalog_service;
        }

        location /orders/ {
            rewrite ^/orders/(.*)$ /$1 break;
            proxy_pass http://order_service;
        }

        location /users/ {
            rewrite ^/users/(.*)$ /$1 break;
            proxy_pass http://user_service;
        }

        location /ai/ {
            rewrite ^/ai/(.*)$ /$1 break;
            proxy_pass http://ai_service;
        }

        location /payments/ {
            rewrite ^/payments/(.*)$ /$1 break;
            proxy_pass http://payment_service;
        }

        location /products/ {
            rewrite ^/products/(.*)$ /$1 break;
            proxy_pass http://product_service;
        }

        location /shipping/ {
            rewrite ^/shipping/(.*)$ /$1 break;
            proxy_pass http://shipping_service;
        }

        location / {
            proxy_pass http://storefront;
        }
    }
}
