# Generated by Django 6.0.4 on 2026-06-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('service_level', models.CharField(default='standard', max_length=80)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=80, unique=True)),
                ('recipient_name', models.CharField(max_length=160)),
                ('recipient_phone', models.CharField(blank=True, max_length=40)),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_city', models.CharField(max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.carrier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
